domain: paulhuggett.github.io
url: https://paulhuggett.github.io
baseurl: /docs/
repository: "paulhuggett/icubaby"

theme: jekyll-theme-dinky
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
