name: RTD
channels:
  - conda-forge
  - defaults
dependencies:
  - breathe
  - doxygen=1.10.0
  - graphviz
  - pip:
    - readthedocs-sphinx-ext
  - python=3.12
  - sphinx=7.2.6
  - sphinx-design=0.5.0

